resources:
  - name: pipelines-demo-image-mini
    type: image
    integration: manishas-dh
    pointer:
      sourceName: "shippablesamples/samplepipelinesdemo"
      isPull: false
    seed:
      versionName: "latest"

jobs:
  - name: runSh-mini-1
    type: runSh
    steps:
      - IN: pipelines-demo-image-mini
      - TASK:
        - echo "hello world"

  - name: runSh-mini-2
    type: runSh
    steps:
      - IN: pipelines-demo-image-mini
      - TASK:
        - echo "hello world"
      
